#!/bin/bash

# Install program and dependencies, if doesn't yet exist.
if [[ -z `command -v "mc"` ]]; then
	# Install Dependencies
	evnDependencies="cvs gcc make autoconf automake libtool libglib2.0-dev libslang2-dev intltool"
	for evnDependency in $evnDependencies; do
		[[ -z command -v ${evnDependency}]] && sudo apt-get install -y ${evnDependency}
	done

	# GetText
	cd $HOME/Downloads
	sudo wget -O - http://ftp.gnu.org/pub/gnu/gettext/gettext-0.18.1.1.tar.gz | tar xzf -
	[[ -d /usr/share/gettext ]] && sudo rm -rf /usr/share/gettext
	sudo mv gettext-0.18.1.1 /usr/share/gettext
	cd /usr/share/gettext
	sudo ./configure
	sudo make
	sudo make install

	# Install Midnight commands via Git repository for latest version.
	cd /usr/local/share
	sudo git clone git://midnight-commander.org/git/mc.git
	cd /usr/local/share/mc
	sudo ./autogen.sh
	sudo ./configure
	sudo make
	sudo make install
done

# Link configurations
ln -s $HOME/Dropbox/Config/mc $HOME/.config/mc                                                ## Move configurations from dropbox
sudo ln -s $HOME/.mc/lib/mc-solarized/solarized.ini /usr/local/share/mc/skins/solarized.ini   ## link skins to their proper place
sudo rm -rf /usr/local/etc/mc && sudo ln -s $HOME/.config/mc/etc /usr/local/etc/mc            ## link configurations to their proper place