#!/bin/bash

# Install program and dependencies, if doesn't yet exist.
if [[ -z `command -v "mc"` ]]; then
	sudo apt-get build-dep mc
	cd /usr/local/src
	sudo git clone https://github.com/MidnightCommander/mc.git
	cd mc
	sudo ./autogen.sh && sudo ./configure && sudo make && sudo make clean install
fi