#!/bin/bash

cp -a $HOME/.config/mc/etc $HOME/.config/mc/etc.bak &&
cd /usr/local/share/mc &&
sudo git reset --hard &&
sudo git pull &&
sudo ./autogen.sh && sudo ./configure && sudo make && sudo make install &&
sudo chown -R $USER:$USER $HOME/.config/mc/etc